import * as path from 'path'
import * as changeCase from 'change-case'
import { Dependency, DependencyOptions, DependencySource } from './dependency'
import { FileNamingStyle } from '~/constants/file-naming-style'
import { toComment } from './to-comment'


const HeaderComment = [
  '// Code generated by keq-cli. DO NOT EDIT.',
  '// Code generated by keq-cli. DO NOT EDIT.',
  '// Code generated by keq-cli. DO NOT EDIT.',
  '',
  '',
].join('\n')

export class Artifact {
  id: string
  filepath: string
  dependencies: Dependency[] = []
  warns: string[] = []
  content: string
  extensionName


  constructor(options: {
    id: string
    filepath: string
    dependencies?: Dependency[]
    content: string
    extensionName?: string
  }) {
    this.id = options.id
    this.filepath = options.filepath
    this.extensionName = options.extensionName || path.extname(options.filepath)
    this.content = options.content

    if (options.dependencies) this.dependencies = options.dependencies
  }

  get dirname(): string {
    return path.dirname(this.filepath)
  }

  changeFileNameCase(style: FileNamingStyle): this {
    this.filepath = this.filepath
      .split('/')
      .map((part, index, arr) => {
        if (part === '.' || part === '..') return part

        if (index !== arr.length - 1) {
          return `${changeCase[style](part)}`
        }

        const baesname = path.basename(part, this.extensionName)
        return `${changeCase[style](baesname)}${this.extensionName}`
      })
      .join('/')

    return this
  }

  relativeTo(filepath: string): string {
    const relativePath = path.relative(filepath, this.filepath)
    return relativePath.startsWith('.') ? relativePath : `./${relativePath}`
  }

  addDependence(source: DependencySource, identifiers: string[], options?: DependencyOptions): Dependency {
    const dependence = new Dependency(
      source,
      identifiers,
      this,
      options,
    )

    this.dependencies.push(dependence)
    return dependence
  }

  addWarn(message: string): void {
    this.warns.push(message)
  }

  toCode(): string {
    let $dependencies = this.dependencies
      .map((dependency) => dependency.toCode())
      .filter((line) => line.trim() !== '')
      .join('\n')

    if ($dependencies) {
      $dependencies += '\n\n'
    }

    let $warns = ''

    if (this.warns.length) {
      $warns = toComment([
        '!!! Here is some Problems !!!',
        '',
        this.warns,
      ].join('\n'))
      $warns += '\n\n'
    }

    return `${HeaderComment}${$warns}${$dependencies}${this.content}`
  }
}
