import * as changeCase from 'change-case'
import { ApiDocumentV3_1 } from '~/models/api-document_v3_1.js'

export interface ApiDocumentNestjsModuleRendererOptions {
  esm?: boolean

  getNestjsClientFilepath(document: ApiDocumentV3_1): string
}

export class NestjsModuleRenderer {
  constructor(
    private readonly document: ApiDocumentV3_1,
    private readonly options: ApiDocumentNestjsModuleRendererOptions,
  ) {
  }

  render(): string {
    const moduleName = changeCase.pascalCase(this.document.module.name)
    const clientFilepath = this.options.getNestjsClientFilepath(this.document)
      .replace(/(\.ts|\.mts|\.cts|\.js|\.cjs|\.mjs)?$/, this.options.esm ? '.js' : '')

    return [
      '',
      '/* @anchor:file:start */',
      'import { Module, ConfigurableModuleBuilder, Provider } from "@nestjs/common"',
      'import { KeqRequest } from "keq"',
      'import { KeqModule, type KeqModuleOptions, KeqConsumer } from "@keq-request/nestjs"',
      `import { ${moduleName}Client } from "${clientFilepath}"`,
      '',
      '',
      `export interface ${moduleName}ModuleOptions extends KeqModuleOptions {`,
      '  /**',
      '   * Whether to register the module globally.',
      '   * @default false',
      '   */',
      '  isGlobal?: boolean',
      '}',
      '',
      `const KEQ_REQUEST_TOKEN = Symbol("${moduleName}KeqRequest")`,
      `const KEQ_CONSUMER_TOKEN = Symbol("${moduleName}KeqConsumer")`,
      '',
      `const { ConfigurableModuleClass, MODULE_OPTIONS_TOKEN } = new ConfigurableModuleBuilder<${moduleName}ModuleOptions>()`,
      '  .setExtras({ isGlobal: false }, (definition, extras) => ({',
      '    ...definition,',
      '    global: extras.isGlobal,',
      '  }))',
      '  .build()',
      '',
      'const REQUEST_PROVIDER: Provider = {',
      '  provide: KEQ_REQUEST_TOKEN,',
      `  useFactory: (options: ${moduleName}ModuleOptions, globalRequest?: KeqRequest) => {`,
      '',
      '    if (!options.isolate && !globalRequest) {',
      `      console.warn("${moduleName}Module: No global KeqRequest found, creating an isolated instance. Import KeqModule globally or set { isolate: true } to suppress this warning.")`,
      '    }',
      '',
      '    const request = (!options.isolate && globalRequest)',
      '      ? globalRequest.fork()',
      '      : new KeqRequest()',
      '',
      '    if (options.middlewares) {',
      '      for (const middleware of options.middlewares) {',
      '        request.use(middleware)',
      '      }',
      '    }',
      '',
      '    return request',
      '  },',
      '  inject: [',
      '    MODULE_OPTIONS_TOKEN,',
      '    { token: KeqRequest, optional: true },',
      '  ],',
      '}',
      '',
      'const CLIENT_PROVIDER: Provider = {',
      `  provide: ${moduleName}Client,`,
      `  useFactory: (request: KeqRequest) => new ${moduleName}Client(request),`,
      '  inject: [KEQ_REQUEST_TOKEN],',
      '}',
      '',
      'const CONSUMER_PROVIDER: Provider = {',
      '  provide: KEQ_CONSUMER_TOKEN,',
      '  useFactory: (request: KeqRequest) => new KeqConsumer(request),',
      '  inject: [KEQ_REQUEST_TOKEN],',
      '}',
      '',
      '/**',
      ` * NestJS module that provides the {@link ${moduleName}Client} for dependency injection.`,
      ' *',
      ' * This module requires a `KeqRequest` instance, which can be provided in two ways:',
      ' *',
      ' * **Option 1: Use the global `KeqModule` (recommended)**',
      ' *',
      ' * Import `KeqModule` globally, then register this module.',
      ' * The module will fork from the global KeqRequest and inherit its middlewares.',
      ' *',
      ' * ```typescript',
      ' * // app.module.ts',
      " * import { KeqModule } from '@keq-request/nestjs'",
      ' * ',
      ' * @Module({',
      ' *   imports: [',
      ' *     KeqModule,',
      ` *     ${moduleName}Module.register({`,
      ' *       isGlobal: true, // optional, default false',
      ' *       middlewares: [], // module-level middlewares',
      ' *     }),',
      ' *   ],',
      ' * })',
      ' * export class AppModule {}',
      ' * ```',
      ' *',
      ' * **Option 2: Provide an isolated `KeqRequest` instance**',
      ' *',
      ' * ```typescript',
      ' * @Module({',
      ' *   imports: [',
      ` *     ${moduleName}Module.register({`,
      ' *       isolate: true, // no inherited middlewares',
      ' *     }),',
      ' *   ],',
      ' * })',
      ' * export class SomeFeatureModule {}',
      ' * ```',
      ' *',
      ' * Then inject `' + moduleName + 'Client` in your services:',
      ' *',
      ' * ```typescript',
      ' * @Injectable()',
      ' * export class SomeService {',
      ` *   constructor(private readonly client: ${moduleName}Client) {}`,
      ' * }',
      ' * ```',
      ' */',
      '@Module({',
      '  imports: [KeqModule],',
      '  providers: [REQUEST_PROVIDER, CONSUMER_PROVIDER, CLIENT_PROVIDER],',
      `  exports: [${moduleName}Client, KEQ_CONSUMER_TOKEN],`,
      '})',
      `export class ${moduleName}Module extends ConfigurableModuleClass {`,
      '  static readonly KEQ_REQUEST = KEQ_REQUEST_TOKEN',
      '  static readonly KEQ_CONSUMER = KEQ_CONSUMER_TOKEN',
      '}',
      '',
      '/* @anchor:file:end */',
    ].join('\n')
  }
}
