import { Compiler } from '~/compiler/index.js'
import { Artifact, OperationDefinition } from '~/models/index.js'
import { Plugin } from '~/types/plugin.js'
import { GenerateMicroFunctionPlugin } from '../generate-micro-function/index.js'


export interface SpringdocCompatPluginOptions {
  /**
   * Ensure application/json requests always carry a body.
   * When enabled, an empty object `{}` is sent even if no body properties are provided.
   * Compatible with Spring Boot Jackson and other backends that require a JSON body.
   * @default false
   */
  ensureJsonBody?: boolean
}


function flattenExtensions(obj: unknown): void {
  if (typeof obj !== 'object' || obj === null) return

  if (Array.isArray(obj)) {
    for (const item of obj) {
      flattenExtensions(item)
    }
    return
  }

  const record = obj as Record<string, unknown>

  if ('extensions' in record && typeof record.extensions === 'object' && record.extensions !== null) {
    const extensions = record.extensions as Record<string, unknown>
    for (const [key, value] of Object.entries(extensions)) {
      if (!(key in record)) {
        record[key] = value
      }
    }
    delete record.extensions
  }

  for (const value of Object.values(record)) {
    flattenExtensions(value)
  }
}

function patchParameterList(parameters: unknown): void {
  if (!Array.isArray(parameters)) return

  for (const param of parameters) {
    if (typeof param !== 'object' || param === null) continue
    if ('$ref' in param) continue

    const record = param as Record<string, unknown>
    if (!('schema' in record) && !('content' in record)) {
      record.schema = {}
    }
  }
}

function ensureParameterSchema(spec: unknown): void {
  if (typeof spec !== 'object' || spec === null) return

  const root = spec as Record<string, unknown>
  const paths = root.paths as Record<string, unknown> | undefined
  if (paths) {
    for (const pathItem of Object.values(paths)) {
      if (typeof pathItem !== 'object' || pathItem === null) continue
      const item = pathItem as Record<string, unknown>

      patchParameterList(item.parameters)

      for (const method of ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace']) {
        const operation = item[method] as Record<string, unknown> | undefined
        if (operation) {
          patchParameterList(operation.parameters)
        }
      }
    }
  }

  const components = root.components as Record<string, unknown> | undefined
  if (components?.parameters) {
    const params = components.parameters as Record<string, unknown>
    for (const param of Object.values(params)) {
      if (typeof param !== 'object' || param === null) continue
      if ('$ref' in param) continue

      const record = param as Record<string, unknown>
      if (!('schema' in record) && !('content' in record)) {
        record.schema = {}
      }
    }
  }
}

function hasJsonContent(operation: OperationDefinition): boolean {
  const content = operation.operation.requestBody?.content
  if (!content || typeof content !== 'object') return false
  return 'application/json' in content
}


/**
 * Compatibility plugin for OpenAPI documents generated by Springdoc (Java/Spring Boot).
 *
 * Springdoc outputs documents with structures that do not conform to the OpenAPI spec.
 * This plugin applies corrections before validation.
 * Current processing:
 * - Flatten nested `extensions` objects into sibling x-* properties
 * - Add `schema: {}` to parameters missing both `schema` and `content`
 * - (Optional) Ensure application/json requests always carry a body
 */
export class SpringdocCompatPlugin implements Plugin {
  constructor(private readonly options: SpringdocCompatPluginOptions = {}) {}

  apply(compiler: Compiler): void {
    compiler.hooks.beforeValidate.tap(SpringdocCompatPlugin.name, (spec) => {
      flattenExtensions(spec)
      ensureParameterSchema(spec)
    })

    if (this.options.ensureJsonBody) {
      this.applyEnsureJsonBody(compiler)
    }
  }

  private applyEnsureJsonBody(compiler: Compiler): void {
    const metadata = GenerateMicroFunctionPlugin.of(compiler)
    if (!metadata) return

    metadata.hooks.afterMicroFunctionArtifactGenerated
      .tap({ name: SpringdocCompatPlugin.name, stage: 100 }, (artifact: Artifact, operationDefinition: OperationDefinition) => {
        if (hasJsonContent(operationDefinition)) {
          artifact.anchor.block.prepend('body', '  void req.send({})')
        }
        return artifact
      })
  }
}
