import * as path from 'path'
import { toComment } from './utils/to-comment.js'
import { Anchor } from './anchor.js'


const HeaderComment = [
  '// Code generated by keq-cli. DO NOT EDIT.',
  '// Code generated by keq-cli. DO NOT EDIT.',
  '// Code generated by keq-cli. DO NOT EDIT.',
  '',
  '',
].join('\n')

export class Artifact {
  id: string
  filepath: string
  warns: string[] = []
  content: string
  extensionName
  anchor = new Anchor(this)

  constructor(options: {
    id: string
    filepath: string
    content: string
    extensionName?: string
  }) {
    this.id = options.id
    this.filepath = options.filepath
    this.extensionName = options.extensionName || path.extname(options.filepath)
    this.content = options.content
  }

  get dirname(): string {
    return path.dirname(this.filepath)
  }

  addWarn(message: string): void {
    this.warns.push(message)
  }

  renderer(): string {
    let $warns = ''

    if (this.warns.length) {
      $warns = toComment([
        '!!! Here is some Problems !!!',
        '',
        this.warns,
      ].join('\n'))
      $warns += '\n\n'
    }

    return `${HeaderComment}${$warns}${this.content}`
  }
}
