import * as path from 'path'
import { Anchor } from './anchor.js'


const HeaderComment = [
  '// Code generated by @keq-request/cli. DO NOT EDIT.',
  '// Code generated by @keq-request/cli. DO NOT EDIT.',
  '// Code generated by @keq-request/cli. DO NOT EDIT.',
].join('\n')

export class Artifact {
  id: string
  filepath: string
  content: string
  extensionName
  anchor = new Anchor(this)

  constructor(options: {
    id: string
    filepath: string
    content: string
    extensionName?: string
  }) {
    this.id = options.id
    this.filepath = options.filepath
    this.extensionName = options.extensionName || path.extname(options.filepath)
    this.content = options.content
  }

  get dirname(): string {
    return path.dirname(this.filepath)
  }

  renderer(): string {
    return `${HeaderComment}\n${this.content}`
  }
}
