on:
  push:
    branches:
      # - main
      - alpha
  workflow_dispatch:

name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  NPM_CONFIG_TAG: "${{ github.ref_name == 'main' && 'latest' || github.ref_name }}"
  NPM_CONFIG_PROVENANCE: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - if: env.NPM_CONFIG_TAG != 'latest' && hashFiles('.changeset/pre.json') == ''
        run: pnpm changeset pre enter ${{ env.NPM_CONFIG_TAG }}

      - if: env.NPM_CONFIG_TAG == 'latest' && hashFiles('.changeset/pre.json') != ''
        run: pnpm changeset pre exit

      - id: changesets
        uses: changesets/action@v1
        with:
          title: "Release"
          commit: "chore: release"
          publish: "pnpm changeset publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN}}

          # NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
